ServiceName: foot
Debug: false
LogLevel: 3

Mysql:
  default:
    Host: rm-abc.mysql.rds.aliyuncs.com
    Port: 3306
    Username: root
    Password: 123456
    Database: demo_foot
    Charset: utf8

RabbitMQ:
  Connection:
    Default:
        Host: 10.10.10.10
        Port: 5672
        User: root
        Password: 123456
        Vhost: /

  Exchange:
    GroupName1:
      ExchangeName: shawn_to_mq
      QueueName: queue_name_1
      RoutingKey: routing_key_1
      ConsumerTag:
    GroupName2:
      ExchangeName: mq_to_shawn
      QueueName: queue_name_2
      RoutingKey: routing_key_2
      ConsumerTag: consumer_mq